server:
  port: 80
  
spring:
  application:
    name: supportServiceGateway
  profiles:
    include: common-config,discovery,feign
  codec:
    max-in-memory-size: 8MB
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 1000
        min-idle: 0
        max-idle: 100
        max-wait: 10000ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      # ======单体服务start
      # ------basic module
#        - id: user
#          uri: lb://basicServiceUser
#          predicates:
#            - Path=/user/**
#        - id: auth
#          uri: lb://basicServiceAuth
#          predicates:
#            - Path=/auth/**

      # ------mall module
#        - id: product
#          uri: lb://mallServiceProduct
#          predicates:
#            - Path=/product/**
#        - id: order
#          uri: lb://mallServiceOrder
#          predicates:
#            - Path=/order/**
      # ======单体服务end

      # ======合体服务start
#        - id: basic
#          uri: lb://merge-basic
#          predicates:
#            - Path=/user/**,/auth/**
#        - id: mall
#          uri: lb://merge-mall
#          predicates:
#            - Path=/product/**,/order/**
      # ======合体服务end