spring:
  application:
    name: supportServiceAdmin
  profiles:
    include: common-config,discovery
  security:
    user:
      name: admin
      password: ZD3jbvwv5Luvnwvk

server:
  port: 10011

smart:
  monitor:
    robotKey: 15228554-fc8e-481f-83bc-1e0992f87aea
    serviceInfos:
      mallServiceOrder:
        id: 16
        robotKey: 15228554-fc8e-481f-83bc-1e0992f87aea
        remindTagMinDiffTs: 2400000
        reminders:
          - Redzhang
          - Markliu
      mallServiceProduct:
        id: 17
        robotKey: 15228554-fc8e-481f-83bc-1edfgs587aea
        remindTagMinDiffTs: 1800000
        reminders:
          - Redzhang
          - Collin