@startuml

skinparam sequenceMessageAlign center
skinparam linetype ortho

package smart-cloud-starter{
    [smart-cloud-monitor]
    [smart-cloud-starter-api-version]
    [smart-cloud-starter-configure]
    [smart-cloud-starter-core]
    [smart-cloud-starter-elasticsearch-dynamic-datasource]
    [smart-cloud-starter-feign]
    [smart-cloud-starter-global-id]
    [smart-cloud-starter-job]
    [smart-cloud-starter-locale]
    [smart-cloud-starter-log4j2]
    [smart-cloud-starter-logback]
    [smart-cloud-starter-method-log]
    [smart-cloud-starter-mock]
    [smart-cloud-starter-mp-shardingjdbc]
    [smart-cloud-starter-mybatis-plus]
    [smart-cloud-starter-rabbitmq]
    [smart-cloud-starter-rate-limit]
    [smart-cloud-starter-redis]
    [smart-cloud-starter-static-discovery]
    [smart-cloud-starter-web]
}

package smart-test {
    [smart-cloud-starter-test]
    [smart-cloud-starter-test-mock-rabbitmq]
    [smart-cloud-test-core]
    [smart-cloud-starter-test-mock-redis]
}

package smart-api-core{
    [smart-api-annotation]
    [smart-user-context]
}

package other {
    [smart-code-generate]
    [smart-common-pojo]
    [smart-common-web]
    [smart-constants]
    [smart-exception]
    [smart-mask]
    [smart-utility]
}

"smart-cloud-starter"-[hidden]>"smart-test"
"smart-cloud-starter"-[hidden]>"smart-api-core"
@enduml